image: "${GLOBAL_IMAGE_NAME}:${GLOBAL_IMAGE_TAG}"

# https://gitlab.com/singletonsd/pipelines/npm
include:
  - project: 'singletonsd/pipelines/npm'
    file: '/src/.gitlab-ci-main.yml'

variables:
  GLOBAL_IMAGE_NAME: "node"
  GLOBAL_IMAGE_TAG: "8-alpine"
  TEST_STATIC_ALL: "true"
  TEST_DYNAMIC_ALL: "true"
  NODE_COMMON_INSTALL_BEFORE: "" #install apk binaries.
  NODE_COMMON_DOCKER_PACKAGE: "true" # To create a push docker images.

stages:
  - install
  - test_static
  - build
  - test_dynamic
  - package
