image: "${TEST_STATIC_IMAGE_NAME}:${TEST_STATIC_IMAGE_TAG}"

variables:
  TEST_STATIC_IMAGE_NAME: "${GLOBAL_IMAGE_NAME:-node}"
  TEST_STATIC_IMAGE_TAG: "${GLOBAL_IMAGE_TAG:-8-alpine}"
  TEST_STATIC_ALL: ""
  TEST_STATIC_LINT: ""
  TEST_STATIC_AUDIT: ""
  TEST_STATIC_CHECK: ""

stages:
  - test_static

test_static:lint:
  stage: test_static
  before_script:
    - if [ ! -d "node_modules" ]; then
        npm i;
      fi
  script:
    - npm run lint
  allow_failure: true
  except:
    - schedules
  only:
    changes:
      - config/**/*
      - "*.json"
      - src/**/*
      - .gitlab-ci.yml
    variables:
      - $TEST_STATIC_ALL == "true"
      - $TEST_STATIC_LINT == "true"

test_static:audit:
  stage: test_static
  before_script:
    - if [ ! -d "node_modules" ]; then
        npm i;
      fi
  script:
    - npm audit
  allow_failure: true
  except:
    - schedules
  only:
    changes:
      - config/**/*
      - "*.json"
      - src/**/*
      - .gitlab-ci.yml
    variables:
      - $TEST_STATIC_ALL == "true"
      - $TEST_STATIC_AUDIT == "true"

test_static:check:
  stage: test_static
  before_script:
    - if [ ! -d "node_modules" ]; then
        npm i;
      fi
  script:
    - npm run check
  allow_failure: true
  except:
    - schedules
  only:
    changes:
      - config/**/*
      - "*.json"
      - src/**/*
      - .gitlab-ci.yml
    variables:
      - $TEST_STATIC_ALL == "true"
      - $TEST_STATIC_CHECK == "true"
